#INCLUDE FOXPRO_REPORTING.H

#INCLUDE REPORTLISTENERS_LOCS.H

* -- constants for VCX super classes 

* --  general constant for debugging
#DEFINE OUTPUTCLASS_DEBUGGING .F.

* -- UtilityReportListener class 

#DEFINE OUTPUTCLASS_READCONFIG_NEITHER           0
#DEFINE OUTPUTCLASS_READCONFIG_INIT              1
#DEFINE OUTPUTCLASS_READCONFIG_REPORT            2
#DEFINE OUTPUTCLASS_READCONFIG_BOTH              3

* -- XML Output Listener class-specific constants

#DEFINE OUTPUTXML_DATA_ONLY 0
#DEFINE OUTPUTXML_RDL_ONLY    1
#DEFINE OUTPUTXML_DATA_RDL    2

#DEFINE OUTPUTXML_BREAKS_INDATA          0
#DEFINE OUTPUTXML_BREAKS_NONE              1
#DEFINE OUTPUTXML_BREAKS_COLLECTION   2

#DEFINE OUTPUTXML_RAW                 0
#DEFINE OUTPUTXML_DOM                  1
#DEFINE OUTPUTXML_DOTNET            2

#DEFINE OUTPUTXML_CHARFIELD_LIMIT 254

#DEFINE OUTPUTXML_XSLTOBJECT_TYPESTRINGS "|document|element|"

* #DEFINE OUTPUTXML_REPEATSPANNEDITEM .T.
* #DEFINE OUTPUTXML_PERFORMLOCALECONVERSION .F.

#DEFINE OUTPUTXML_CONTINUATION (THIS.NoPageEject OR ;
                               (VARTYPE(THIS.CommandClauses) = "O" AND ;
                               THIS.CommandClauses.NoPageEject))

* supplied superclasses' tunable settings

#DEFINE OUTPUTCLASS_INTERNALDBF  "_ReportOutputConfig"
#DEFINE OUTPUTCLASS_EXTERNALDBF  "OutputConfig"

#DEFINE OUTPUTCLASS_OBJTYPE_CONFIG         1000

#DEFINE OUTPUTCLASS_STATUSCHAR_PCT_DONE         [|]
#DEFINE OUTPUTCLASS_STATUSCHAR_PCT_NOT_DONE     [.]     
#DEFINE OUTPUTCLASS_ONE_HUNDRED_PCT_MARK        50

#DEFINE OUTPUTCLASS_FILENAME_CHARS_DISALLOWED  [?*"<>|]

* -- XML Output Listener-specific user-tunable settings

#DEFINE OUTPUTXML                                  OUTPUTXML_RAW

#DEFINE OUTPUTXML_OBJTYPE_NODES       1100
#DEFINE OUTPUTXML_OBJTYPE_BANDOFFSET   500
#DEFINE OUTPUTXML_OBJCODE_DOC          100
#DEFINE OUTPUTXML_OBJCODE_DATA         200
#DEFINE OUTPUTXML_OBJCODE_RDL          300
#DEFINE OUTPUTXML_OBJCODE_PAGES        400
#DEFINE OUTPUTXML_OBJCODE_COLS         500
#DEFINE OUTPUTXML_OBJCODE_ATTRIBMEMBER 600


#DEFINE OUTPUTXML_GOOFTAG  "XXXX"
     
#DEFINE OUTPUTXML_DOMDOCUMENTOBJECT "Msxml2.FreeThreadedDOMDocument.4.0"
#DEFINE OUTPUTXML_DOMFREETHREADED_DOCUMENTOBJECT "Msxml2.FreeThreadedDOMDocument.4.0"
#DEFINE OUTPUTXML_XSLT_PROCESSOROBJECT "Msxml2.XSLTemplate.4.0"



